import Layout from '@/components/Layout'
import Head from 'next/head'
import Image from 'next/image'
import profilepic from '../../public/images/profile/my.png'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import TransitionEffect from '@/components/TransitionEffect'
// import lightBulb from '../../public/images/svgs/miscellaneous_icons_1.svg'

export default function Home() {
  return (
    <>
      <Head>
        <title>Sahan Panangamu</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
      <main className='flex items-center text-dark w-full min-h-screen dark:text-light'>
        <Layout className='pt-0 md:pt-16 sm:pt-8 mt-10'>
          <div

            className='flex items-center justify-between w-full lg:flex-col bg-gradient-to-b from-red-100 to-red-500 dark:from-zinc-500 dark:to-slate-800'>
            <div className="w-1/2 md:w-full">
              <Image src={profilepic} alt='Dhananjaya' className='w-full h-auto lg:hidden md:inline-block md:w-full'
                priority
                sizes="(max-width: 768px) 100vw,
                (max-width: 1200px) 50vw,
                50vw"
              />
            </div>
            <div className="w-1/2 flex flex-col items-center self-center lg:w-full lg:text-center">
              <AnimatedText text="Ensuring software perfection through rigorous testing and analysis." className='!text:6xl !text-left lg:pt-5 
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              ' />
              <p className='my-4 text-base font-medium md:text-sm sm:text-xs sm:px-5'>
                As a software automation tester, my primary responsibility is delivering bug-free software to end-users. Through automated testing processes and meticulous analysis, I ensure that the software meets quality standards.
                This guarantees a seamless user experience and instills confidence in the reliability of the product.
              </p>

              <div className='flex items-center self-start mt-2 lg:self-center lg:mb-5'>

                <Link
                  href='/Resume.pdf'
                  target={"_blank"}
                  className='flex items-center bg-dark text-light p-2.5 px-6 rounded-lg 
                text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid 
                border-transparent hover:border-dark  hover:dark:border-dark md:p-2 md:px-4 md:text-base'
                  download={true}>Resume <LinkArrow className={'w-6 ml-1'} /></Link>

                <Link href='mailto:jsahan.lakmal@gmail.com'
                  target={"_blank"} className='ml-8 text-lg font-medium capitalize text-dark dark:text-light
                underline hover:text-light hover:dark:text-dark md:text-base'>Contact</Link>
              </div>
            </div>

          </div>
        </Layout>

        {/* <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24'>
          <Image src={lightBulb} alt='Dhananjaya' className='w-full h-auto' />
        </div> */}
      </main >
    </>
  )
}
